### PR TITLE
ci: adding url-validator via github actions

### PR DESCRIPTION
**Pull request by ScriptAutomate**
URL validator addition to the repo. This includes an auditor that runs against new PRs, and also includes all the fixes I needed to add based on broken links.

Follow-up issue, based on findings, as it would make sense to make use of a different broken-link checking tool: #183

### CODE REVIEW

**Comment by ScriptAutomate** [comment]
Made progress, saving a checkpoint. Not sure what to do about:

```
[./vault/dendron.dev.api.seeds.md]
- Failed (404): https://github.com/dendronhq/dendron/blob/master/packages/seeds-core/src/base.ts#L39
```

I'm not sure where the code has since moved.

**Comment by ScriptAutomate** [comment]
Also need assistance with:

## Test-related links

```
[./vault/dendron.dev.cook.md]
- Failed (404): https://github.com/dendronhq/dendron/blob/master/packages/engine-server/src/__tests__/enginev2.spec.ts#L652:L652
- Failed (404): https://github.com/dendronhq/dendron/blob/master/packages/plugin-core/src/test/suite-integ/RenameNoteV2.test.ts#L157:L157

[./vault/pkg.dendron-plugin.qa.test.md]
- Failed (404): https://github.com/dendronhq/dendron/blob/master/packages/plugin-core/src/test/suite-integ/RenameNoteV2.test.ts#L131:L131

[./vault/pkg.dendron-engine.qa.md]
- Failed (404): https://www.kevinslin.com/notes/09b6c659-3fe3-4a7d-98f9-47e7167cca5b.html
```

## Cookbook: AWS Amplify examples

```
[./vault/dendron.guides.cook.md]
- Could not connect: https://main.d19svbygngqnpb.amplifyapp.com/
- Failed (404): https://github.com/dendronhq/dendron-amplify-template/generate
```
## API server

```
[./vault/pkg.api-publish.arch.md]
- Failed (404): https://github.com/dendronhq/dendron-backend/blob/main/packages/api-publish/server/serve-lambda.ts#L10:L10
```

## Misc

Related issue:
- https://github.com/mdn/content/issues/3780#issuecomment-913046180

> Note: I replaced our docs link to be to the internet archive version of the page, since the page no longer looks to exist

**Comment by kevinslin** [comment]
## Test Related Links

[./vault/dendron.dev.cook.md]
- Failed (404): https://github.com/dendronhq/dendron/blob/master/packages/engine-server/src/__tests__/enginev2.spec.ts#L652:L652
> https://github.com/dendronhq/dendron/blob/16b0e5c59e3ee11530199b5c9a11a58f05e14a93/packages/engine-test-utils/src/__tests__/engine-server/enginev2.spec.ts
- Failed (404): https://github.com/dendronhq/dendron/blob/master/packages/plugin-core/src/test/suite-integ/RenameNoteV2.test.ts#L157:L157
> removed

[./vault/pkg.dendron-plugin.qa.test.md]
- Failed (404): https://github.com/dendronhq/dendron/blob/master/packages/plugin-core/src/test/suite-integ/RenameNoteV2.test.ts#L131:L131
> removed

[./vault/pkg.dendron-engine.qa.md]
- Failed (404): https://www.kevinslin.com/notes/09b6c659-3fe3-4a7d-98f9-47e7167cca5b.html
> removed

## Cookbook: AWS Amplify examples
- [terminology](https://www.kevinslin.com/notes/09b6c659-3fe3-4a7d-98f9-47e7167cca5b.html) to understand -> remove, this is taken down
- https://main.d19svbygngqnpb.amplifyapp.com/ -> remove, taken down

[./vault/pkg.api-publish.arch.md]
- Failed (404): https://github.com/dendronhq/dendron-backend/blob/main/packages/api-publish/server/serve-lambda.ts#L10:L10
> Not public yet, we can ignore

[./vault/dendron.dev.api.seeds.md]
- Failed (404): https://github.com/dendronhq/dendron/blob/master/packages/seeds-core/src/base.ts#L39
> Remove

**Comment by ScriptAutomate** [comment]
GitHub doesn't like all the calls this is doing against it, and `brok` doesn't have much support for customizing output around particular status returns. **I'm going to add it to `.brokignore` for now so that this PR passes without the 429 failures.**

I'm going to make a follow-up issue that could enhance the URL validator approach, in the future, with some starter commands that I'd have to experiment with at a later date. This approach would allow for internal links as well as external links, and would ensure that the site can build without errors. It seemed like using `blc`, or other `npm` based tool would be more forward thinking in case anything like `dendron-cli` would be extended to make use of the package (or similar package).

```bash
# container
# node:14-bullseye-slim
npm install broken-link-checker
npm install serve
npm install @dendronhq/dendron-cli@latest
npm install @dendronhq/dendron-11ty@latest
npx dendron-cli buildSiteV2 --wsRoot .  --stage prod
npx serve 2>> /dev/null &
blc http://localhost:5000/notes -ro --exclude-internal > output-internal.log
blc http://localhost:5000/notes -ro --exclude-external > output-external.log
```

**Pull request merged**
